name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com
          ECR_REPOSITORY: hello-world-app
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to ECS
        env:
          AWS_REGION: <region>
          ECS_CLUSTER: hello-world-cluster
          ECS_SERVICE: hello-world-service
          ECS_TASK_DEFINITION: hello-world-task
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
